/*
 *=================================================================================================
 * User Constants
 *=================================================================================================
 */
export const GET_USERS = 'GET_USERS';
export const USERS_PAGE_UNLOAD = 'USERS_PAGE_UNLOAD';
export const GET_USERS_REJECTED = 'GET_USERS_REJECTED';
export const GET_USERS_FULFILLED = 'GET_USERS_FULFILLED';
export const GET_DETAIL_USER = 'GET_DETAIL_USER';
export const GET_DETAIL_USER_REJECTED = 'GET_DETAIL_USER_REJECTED';
export const GET_DETAIL_USER_FULFILLED = 'GET_DETAIL_USER_FULFILLED';
export const DELETE_USER = 'DELETE_USER';
export const DELETE_USER_PENDING = 'DELETE_USER_PENDING';
export const DELETE_USER_REJECTED = 'DELETE_USER_REJECTED';
export const DELETE_USER_FULFILLED = 'DELETE_USER_FULFILLED';
export const BLOCK_USER = 'BLOCK_USER';
export const BLOCK_USER_PENDING = 'BLOCK_USER_PENDING';
export const BLOCK_USER_REJECTED = 'BLOCK_USER_REJECTED';
export const BLOCK_USER_FULFILLED = 'BLOCK_USER_FULFILLED';
export const FILTER_USERS = 'FILTER_USERS';
export const FILTER_USERS_REJECTED = 'FILTER_USERS_REJECTED';
export const FILTER_USERS_FULFILLED = 'FILTER_USERS_FULFILLED';
export const SEARCH_USERS = 'SEARCH_USERS';
export const SEARCH_USERS_REJECTED = 'SEARCH_USERS_REJECTED';
export const SEARCH_USERS_FULFILLED = 'SEARCH_USERS_FULFILLED';
export const LOAD_USER_COMMENTS = 'LOAD_USER_COMMENTS';
export const LOAD_USER_COMMENTS_FULFILLED = 'LOAD_USER_COMMENTS_FULFILLED';
export const LOAD_USER_COMMENTS_REJECTED = 'LOAD_USER_COMMENTS_REJECTED';
export const APPROVE_USER_COMMENT = 'APPROVE_USER_COMMENT';
export const APPROVE_USER_COMMENT_FULFILLED = 'APPROVE_USER_COMMENT_FULFILLED';
export const APPROVE_USER_COMMENT_REJECTED = 'APPROVE_USER_COMMENT_REJECTED';
export const BLOCK_USER_COMMENT = 'BLOCK_USER_COMMENT';
export const BLOCK_USER_COMMENT_FULFILLED = 'BLOCK_USER_COMMENT_FULFILLED';
export const BLOCK_USER_COMMENT_REJECTED = 'BLOCK_USER_COMMENT_REJECTED';

// User Admins
export const GET_USER_ADMINS = 'GET_USER_ADMINS';
export const GET_USER_ADMINS_FULFILLED = 'GET_USER_ADMINS_FULFILLED';
export const GET_USER_ADMINS_REJECTED = 'GET_USER_ADMINS_REJECTED';
export const USER_ADMIN_UNLOAD = 'USER_ADMIN_UNLOAD';
export const CREATE_USER_ADMIN = 'CREATE_USER_ADMIN';
export const CREATE_USER_ADMIN_FULFILLED = 'CREATE_USER_ADMIN_FULFILLED';
export const CREATE_USER_ADMIN_REJECTED = 'CREATE_USER_ADMIN_REJECTED';
export const CREATE_USER_ADMIN_PENDING = 'CREATE_USER_ADMIN_PENDING';
export const USER_ADMIN_REDIRECT = 'USER_ADMIN_REDIRECT';
export const UPDATE_USER_ADMIN = 'UPDATE_USER_ADMIN';
export const UPDATE_USER_ADMIN_FULFILLED = 'UPDATE_USER_ADMIN_FULFILLED';
export const UPDATE_USER_ADMIN_REJECTED = 'UPDATE_USER_ADMIN_REJECTED';
export const UPDATE_USER_ADMIN_PENDING = 'UPDATE_USER_ADMIN_PENDING';

/*
 *=================================================================================================
 * Auth and Common Constants
 *=================================================================================================
 */
export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';
export const REGISTER = 'REGISTER';
export const LOGIN_REJECTED = 'LOGIN_REJECTED';
export const LOGIN_FULFILLED = 'LOGIN_FULFILLED';
export const REDIRECT = 'REDIRECT';
export const APP_REDIRECT = 'APP_REDIRECT';
export const APP_LOAD = 'APP_LOAD';
export const APP_LOAD_REJECTED = 'APP_LOAD_REJECTED';
export const APP_LOAD_FULFILLED = 'APP_LOAD_FULFILLED';
export const LOGIN_LOAD = 'LOGIN_LOAD';
export const LOGIN_LOAD_REJECTED = 'LOGIN_LOAD_REJECTED';
export const LOGIN_LOAD_FULFILLED = 'LOGIN_LOAD_FULFILLED';
export const LOGIN_UNLOAD = 'LOGIN_UNLOAD';

/*
 *=================================================================================================
 * Get Log Auction Winner
 *=================================================================================================
 */

export const GET_LOG_AUCTION_WINER = 'GET_LOG_AUCTION_WINER';
export const GET_LOG_AUCTION_WINER_FULFILLED =
  'GET_LOG_AUCTION_WINER_FULFILLED';
export const GET_LOG_AUCTION_WINER_EJECTED = 'GET_LOG_AUCTION_WINER_EJECTED';
export const LOG_AUCTION_WINER_UNLOAD = 'LOG_AUCTION_WINER_UNLOAD';
export const LOG_AUCTION_WINER_UNLOAD_REJECTED =
  'LOG_AUCTION_WINER_UNLOAD_REJECTED';
export const LOG_AUCTION_WINER_UNLOAD_FULFILLED =
  'LOG_AUCTION_WINER_UNLOAD_FULFILLED';

/*
 *=================================================================================================
 * Get Condition
 *=================================================================================================
 */

export const GET_CONDITIONS = 'GET_CONDITIONS';
export const GET_CONDITIONS_FULFILLED = 'GET_CONDITIONS_FULFILLED';
export const GET_CONDITIONS_REJECTED = 'GET_CONDITIONS_REJECTED';
//create
export const CREATE_CONDITION = 'CREATE_CONDITION';
export const CREATE_CONDITION_FULFILLED = 'CREATE_CONDITION_FULFILLED';
export const CREATE_CONDITION_REJECTED = 'CREATE_CONDITION_REJECTED';
//get condition
export const GET_CONDITION = 'GET_CONDITION';
export const GET_CONDITION_FULFILLED = 'GET_CONDITION_FULFILLED';
export const GET_CONDITION_REJECTED = 'GET_CONDITION_REJECTED';
//delete
export const DELETE_CONDITION = 'DELETE_CONDITION';
export const DELETE_CONDITION_PENDING = 'DELETE_CONDITION_PENDING';
export const DELETE_CONDITION_REJECTED = 'DELETE_CONDITION_REJECTED';
export const DELETE_CONDITION_FULFILLED = 'DELETE_CONDITION_FULFILLED';
export const EDIT_CONDITION_LOAD = 'EDIT_CONDITION_LOAD';
export const EDIT_CONDITION_LOAD_REJECTED = 'EDIT_CONDITION_LOAD_REJECTED';
export const EDIT_CONDITION_LOAD_FULFILLED = 'EDIT_CONDITION_LOAD_FULFILLED';
export const UPDATE_CONDITION = 'UPDATE_CONDITION';
export const CONDITION_PAGE_UNLOAD = 'CONDITION_PAGE_UNLOAD';
export const UPDATE_CONDITION_REJECTED = 'UPDATE_CONDITION_REJECTED';
export const UPDATE_CONDITION_FULFILLED = 'UPDATE_CONDITION_FULFILLED';
export const UPDATE_CONDITION_PENDING = 'UPDATE_CONDITION_PENDING';

/*
 *=================================================================================================
 * Auction Constants
 *=================================================================================================
 */
export const GET_AUCTIONS = 'GET_AUCTIONS';
export const GET_AUCTIONS_FULFILLED = 'GET_AUCTIONS_FULFILLED';
export const GET_AUCTIONS_REJECTED = 'GET_AUCTIONS_REJECTED';
export const GET_AUCTION = 'GET_AUCTION';
export const GET_AUCTION_FULFILLED = 'GET_AUCTION_FULFILLED';
export const GET_AUCTION_REJECTED = 'GET_AUCTION_REJECTED';
export const DELETE_AUCTION = 'DELETE_AUCTION';
export const DELETE_AUCTION_FULFILLED = 'DELETE_AUCTION_FULFILLED';
export const DELETE_AUCTION_REJECTED = 'DELETE_AUCTION_REJECTED';
export const CREATE_AUCTION = 'CREATE_AUCTION';
export const CREATE_AUCTION_FULFILLED = 'CREATE_AUCTION_FULFILLED';
export const CREATE_AUCTION_REJECTED = 'CREATE_AUCTION_REJECTED';
export const EDIT_AUCTION = 'EDIT_AUCTION';
export const EDIT_AUCTION_FULFILLED = 'EDIT_AUCTION_FULFILLED';
export const EDIT_AUCTION_REJECTED = 'EDIT_AUCTION_REJECTED';
export const GET_AUCTION_PRODUCTS = 'GET_AUCTION_PRODUCTS';
export const GET_AUCTION_PRODUCTS_REJECTED = 'GET_AUCTION_PRODUCTS_REJECTED';
export const GET_AUCTION_PRODUCTS_FULFILLED = 'GET_AUCTION_PRODUCTS_FULFILLED';
export const GET_USERS_TO_ARRAY = 'GET_USERS_TO_ARRAY';
export const GET_USERS_TO_ARRAY_FULFILLED = 'GET_USERS_TO_ARRAY_FULFILLED';
export const LOAD_EDIT_AUCTION = 'LOAD_EDIT_AUCTION';
export const LOAD_EDIT_AUCTION_FULFILLED = 'LOAD_EDIT_AUCTION_FULFILLED';
export const LOAD_EDIT_AUCTION_REJECTED = 'LOAD_EDIT_AUCTION_REJECTED';
export const UPDATE_AUCTION = 'UPDATE_AUCTION';
export const UPDATE_AUCTION_FULFILLED = 'UPDATE_AUCTION_FULFILLED';
export const UPDATE_AUCTION_REJECTED = 'UPDATE_AUCTION_REJECTED';
export const AUCTIONS_PAGE_UNLOAD = 'AUCTIONS_PAGE_UNLOAD';
export const BLOCK_AUCTION = 'BLOCK_AUCTION';
export const BLOCK_AUCTION_FULFILLED = 'BLOCK_AUCTION_FULFILLED';
export const BLOCK_AUCTION_REJECTED = 'BLOCK_AUCTION_REJECTED';
export const FILTER_AUCTION = 'FILTER_AUCTION';
export const FILTER_AUCTION_FULFILLED = 'FILTER_AUCTION_FULFILLED';
export const FILTER_AUCTION_REJECTED = 'FILTER_AUCTION_REJECTED';
export const SEARCH_AUCTION = 'SEARCH_AUCTION';
export const SEARCH_AUCTION_FULFILLED = 'SEARCH_AUCTION_FULFILLED';
export const SEARCH_AUCTION_REJECTED = 'SEARCH_AUCTION_REJECTED';
export const GET_ALL_PRODUCTS = 'GET_ALL_PRODUCTS';
export const GET_ALL_PRODUCTS_FULFILLED = 'GET_ALL_PRODUCTS_FULFILLED';
export const GET_ALL_PRODUCTS_REJECTED = 'GET_ALL_PRODUCTS_REJECTED';
export const FILTER_AUCTION_BY_PRODUCT = 'FILTER_AUCTION_BY_PRODUCT';
export const FILTER_AUCTION_BY_PRODUCT_FULFILLED =
  'FILTER_AUCTION_BY_PRODUCT_FULFILLED';
export const FILTER_AUCTION_BY_PRODUCT_REJECTED =
  'FILTER_AUCTION_BY_PRODUCT_REJECTED';

/*
 *=================================================================================================
 * Product Constants
 *=================================================================================================
 */

// Lists
export const GET_PRODUCTS = 'GET_PRODUCTS';
export const GET_PRODUCTS_REJECTED = 'GET_PRODUCTS_REJECTED';
export const GET_PRODUCTS_FULFILLED = 'GET_PRODUCTS_FULFILLED';
// Unload
export const PRODUCTS_PAGE_UNLOAD = 'PRODUCTS_PAGE_UNLOAD';
// Show
export const GET_DETAIL_PRODUCT = 'GET_DETAIL_PRODUCT';
export const GET_DETAIL_PRODUCT_REJECTED = 'GET_DETAIL_PRODUCT_REJECTED';
export const GET_DETAIL_PRODUCT_FULFILLED = 'GET_DETAIL_PRODUCT_FULFILLED';
// Delete
export const DELETE_PRODUCT = 'DELETE_PRODUCT';
export const DELETE_PRODUCT_REJECTED = 'DELETE_PRODUCT_REJECTED';
export const DELETE_PRODUCT_FULFILLED = 'DELETE_PRODUCT_FULFILLED';
export const DELETE_PRODUCT_PENDING = 'DELETE_PRODUCT_PENDING';
// Create
export const GET_CATEGORIES_CONDITIONS = 'GET_CATEGORIES_CONDITIONS';
export const GET_CATEGORIES_CONDITIONS_REJECTED =
  'GET_CATEGORIES_CONDITIONS_REJECTED';
export const GET_CATEGORIES_CONDITIONS_FULFILLED =
  'GET_CATEGORIES_CONDITIONS_FULFILLED';
export const CREATE_PRODUCT = 'CREATE_PRODUCT';
export const CREATE_PRODUCT_REJECTED = 'CREATE_PRODUCT_REJECTED';
export const CREATE_PRODUCT_FULFILLED = 'CREATE_PRODUCT_FULFILLED';
export const CREATE_PRODUCT_PENDING = 'CREATE_PRODUCT_PENDING';
// Update
export const LOAD_EDIT_PRODUCT = 'LOAD_EDIT_PRODUCT';
export const LOAD_EDIT_PRODUCT_REJECTED = 'LOAD_EDIT_PRODUCT_REJECTED';
export const LOAD_EDIT_PRODUCT_FULFILLED = 'LOAD_EDIT_PRODUCT_FULFILLED';
export const UPDATE_PRODUCT = 'UPDATE_PRODUCT';
export const UPDATE_PRODUCT_REJECTED = 'UPDATE_PRODUCT_REJECTED';
export const UPDATE_PRODUCT_FULFILLED = 'UPDATE_PRODUCT_FULFILLED';
export const UPDATE_PRODUCT_PENDING = 'UPDATE_PRODUCT_PENDING';
// Search
export const SEARCH_PRODUCT = 'SEARCH_PRODUCT';
export const SEARCH_PRODUCT_REJECTED = 'SEARCH_PRODUCT_REJECTED';
export const SEARCH_PRODUCT_FULFILLED = 'SEARCH_PRODUCT_FULFILLED';
// Filter
export const FILTER_PRODUCT = 'FILTER_PRODUCT';
export const FILTER_PRODUCT_REJECTED = 'FILTER_PRODUCT_REJECTED';
export const FILTER_PRODUCT_FULFILLED = 'FILTER_PRODUCT_FULFILLED';

// PRODUCT CATEGORY
export const GET_PRODUCT_CATEGORIES = 'GET_PRODUCT_CATEGORIES';
export const GET_PRODUCT_CATEGORIES_FULFILLED =
  'GET_PRODUCT_CATEGORIES_FULFILLED';
export const GET_PRODUCT_CATEGORIES_REJECTED =
  'GET_PRODUCT_CATEGORIES_REJECTED';
export const PRODUCT_CATEGORIES_UNLOAD = 'PRODUCT_CATEGORIES_UNLOAD';
export const POST_PRODUCT_CATEGORY = 'POST_PRODUCT_CATEGORY';
export const POST_PRODUCT_CATEGORY_FULFILLED =
  'POST_PRODUCT_CATEGORY_FULFILLED';
export const POST_PRODUCT_CATEGORY_REJECTED = 'POST_PRODUCT_CATEGORY_REJECTED';
export const DELETE_PRODUCT_CATEGORY = 'DELETE_PRODUCT_CATEGORY';
export const DELETE_PRODUCT_CATEGORY_FULFILLED =
  'DELETE_PRODUCT_CATEGORY_FULFILLED';
export const DELETE_PRODUCT_CATEGORY_REJECTED =
  'DELETE_PRODUCT_CATEGORY_REJECTED';

/*
 *=================================================================================================
 * Campaign Constants
 *=================================================================================================
 */
export const GET_CAMPAIGNS = 'GET_CAMPAIGNS';
export const GET_CAMPAIGNS_PENDING = 'GET_CAMPAIGNS_PENDING';
export const GET_CAMPAIGNS_REJECTED = 'GET_CAMPAIGNS_REJECTED';
export const GET_CAMPAIGNS_FULFILLED = 'GET_CAMPAIGNS_FULFILLED';

export const CREATE_CAMPAIGN = 'CREATE_CAMPAIGN';
export const CREATE_CAMPAIGN_PENDING = 'CREATE_CAMPAIGN_PENDING';
export const CREATE_CAMPAIGN_REJECTED = 'CREATE_CAMPAIGN_REJECTED';
export const CREATE_CAMPAIGN_FULFILLED = 'CREATE_CAMPAIGN_FULFILLED';

export const DELETE_CAMPAIGN = 'DELETE_CAMPAIGN';
export const DELETE_CAMPAIGN_PENDING = 'DELETE_CAMPAIGN_PENDING';
export const DELETE_CAMPAIGN_REJECTED = 'DELETE_CAMPAIGN_REJECTED';
export const DELETE_CAMPAIGN_FULFILLED = 'DELETE_CAMPAIGN_FULFILLED';

// Unload
export const CAMPAIGNS_PAGE_UNLOAD = 'CAMPAIGNS_PAGE_UNLOAD';
// Show
export const GET_DETAIL_CAMPAIGN = 'GET_DETAIL_CAMPAIGN';
export const GET_DETAIL_CAMPAIGN_REJECTED = 'GET_DETAIL_CAMPAIGN_REJECTED';
export const GET_DETAIL_CAMPAIGN_FULFILLED = 'GET_DETAIL_CAMPAIGN_FULFILLED';
// Filter
export const FILTER_CAMPAIGN = 'FILTER_CAMPAIGN';
export const FILTER_CAMPAIGN_REJECTED = 'FILTER_CAMPAIGN_REJECTED';
export const FILTER_CAMPAIGN_FULFILLED = 'FILTER_CAMPAIGN_FULFILLED';
// Edit
export const EDIT_CAMPAIGN_LOAD = 'EDIT_CAMPAIGN_LOAD';
export const EDIT_CAMPAIGN_LOAD_REJECTED = 'EDIT_CAMPAIGN_LOAD_REJECTED';
export const EDIT_CAMPAIGN_LOAD_FULFILLED = 'EDIT_CAMPAIGN_LOAD_FULFILLED';
export const UPDATE_CAMPAIGN = 'UPDATE_CAMPAIGN';
export const UPDATE_CAMPAIGN_REJECTED = 'UPDATE_CAMPAIGN_REJECTED';
export const UPDATE_CAMPAIGN_FULFILLED = 'UPDATE_CAMPAIGN_FULFILLED';
export const UPDATE_CAMPAIGN_PENDING = 'UPDATE_CAMPAIGN_PENDING';
// Reset redirect
export const CAMPAIGN_RESET_REDIRECT = 'CAMPAIGN_RESET_REDIRECT';

/*
 *=================================================================================================
 * Review Constants
 *=================================================================================================
 */
export const GET_REVIEWS = 'GET_REVIEWS';
export const GET_REVIEWS_FULFILLED = 'GET_REVIEWS_FULFILLED';
export const BLOCK_REVIEW = 'BLOCK_REVIEW';
export const BLOCK_REVIEW_FULFILLED = 'BLOCK_REVIEW_FULFILLED';
export const BLOCK_REVIEW_REJECTED = 'BLOCK_REVIEW_REJECTED';
export const APPROVE_REVIEW = 'APPROVE_REVIEW';
export const APPROVE_REVIEW_REJECTED = 'APPROVE_REVIEW_REJECTED';
export const APPROVE_REVIEW_FULFILLED = 'APPROVE_REVIEW_FULFILLED';
export const DELETE_REVIEW = 'DELETE_REVIEW';
export const DELETE_REVIEW_PENDING = 'DELETE_REVIEW_PENDING';
export const DELETE_REVIEW_REJECTED = 'DELETE_REVIEW_REJECTED';
export const DELETE_REVIEW_FULFILLED = 'DELETE_REVIEW_FULFILLED';

/*
 *=================================================================================================
 * Message Constants
 *=================================================================================================
 */

export const CREATE_MESSAGE = 'CREATE_MESSAGE';
export const CREATE_MESSAGE_PENDING = 'CREATE_MESSAGE_PENDING';
export const CREATE_MESSAGE_REJECTED = 'CREATE_MESSAGE_REJECTED';
export const CREATE_MESSAGE_FULFILLED = 'CREATE_MESSAGE_FULFILLED';

export const GET_MESSAGE_CATEGORIES = 'GET_MESSAGE_CATEGORIES';
export const GET_MESSAGE_CATEGORIES_FULFILLED =
  'GET_MESSAGE_CATEGORIES_FULFILLED';
export const GET_MESSAGE_CATEGORIES_REJECTED =
  'GET_MESSAGE_CATEGORIES_REJECTED';

export const GET_MESSAGES = 'GET_MESSAGES';
export const GET_MESSAGES_FULFILLED = 'GET_MESSAGES_FULFILLED';
export const GET_MESSAGES_REJECTED = 'GET_MESSAGES_REJECTED';
export const GET_MESSAGE = 'GET_MESSAGE';
export const GET_MESSAGE_FULFILLED = 'GET_MESSAGE_FULFILLED';
export const GET_MESSAGE_REJECTED = 'GET_MESSAGE_REJECTED';
export const DELETE_MESSAGE = 'DELETE_MESSAGE';
export const DELETE_MESSAGE_PENDING = 'DELETE_MESSAGE_PENDING';
export const DELETE_MESSAGE_REJECTED = 'DELETE_MESSAGE_REJECTED';
export const DELETE_MESSAGE_FULFILLED = 'DELETE_MESSAGE_FULFILLED';
export const EDIT_MESSAGE_LOAD = 'EDIT_MESSAGE_LOAD';
export const EDIT_MESSAGE_LOAD_REJECTED = 'EDIT_MESSAGE_LOAD_REJECTED';
export const EDIT_MESSAGE_LOAD_FULFILLED = 'EDIT_MESSAGE_LOAD_FULFILLED';
export const UPDATE_MESSAGE = 'UPDATE_MESSAGE';
export const UPDATE_MESSAGE_REJECTED = 'UPDATE_MESSAGE_REJECTED';
export const UPDATE_MESSAGE_FULFILLED = 'UPDATE_MESSAGE_FULFILLED';
export const UPDATE_MESSAGE_PENDING = 'UPDATE_MESSAGE_PENDING';
export const CATEGORY_MESSAGE_LOAD = 'CATEGORY_MESSAGE_LOAD';
export const CATEGORY_MESSAGE_FULFILLED = 'CATEGORY_MESSAGE_FULFILLED';
export const CATEGORY_MESSAGE_REJECTED = 'CATEGORY_MESSAGE_REJECTED';
export const MESSAGES_PAGE_UNLOAD = 'MESSAGES_PAGE_UNLOAD';

/*
 *=================================================================================================
 *  Contact Constants
 *=================================================================================================
 */

export const CONTACTS_PAGE_UNLOAD = 'CONTACTS_PAGE_UNLOAD';
export const CONTACT_RESET_REDIRECT = 'CONTACT_RESET_REDIRECT';

export const GET_CONTACTS = 'GET_CONTACTS';
export const GET_CONTACTS_FULFILLED = 'GET_CONTACTS_FULFILLED';
export const GET_CONTACTS_REJECTED = 'GET_CONTACTS_REJECTED';

export const GET_DETAIL_CONTACT = 'GET_DETAIL_CONTACT';
export const GET_DETAIL_CONTACT_FULFILLED = 'GET_DETAIL_CONTACT_FULFILLED';
export const GET_DETAIL_CONTACT_REJECTED = 'GET_DETAIL_CONTACT_REJECTED';

export const REPLY_CONTACT = 'REPLY_CONTACT';
export const REPLY_CONTACT_PENDING = 'REPLY_CONTACT_PENDING';
export const REPLY_CONTACT_FULFILLED = 'REPLY_CONTACT_FULFILLED';
export const REPLY_CONTACT_REJECTED = 'REPLY_CONTACT_REJECTED';

export const DELETE_CONTACT = 'DELETE_CONTACT';
export const DELETE_CONTACT_PENDING = 'DELETE_CONTACT_PENDING';
export const DELETE_CONTACT_REJECTED = 'DELETE_CONTACT_REJECTED';
export const DELETE_CONTACT_FULFILLED = 'DELETE_CONTACT_FULFILLED';

/*
 *=================================================================================================
 *  Contact Category Constants
 *=================================================================================================
 */
export const GET_CONTACT_CATEGORIES = 'GET_CONTACT_CATEGORIES';
export const GET_CONTACT_CATEGORIES_FULFILLED =
  'GET_CONTACT_CATEGORIES_FULFILLED';
export const GET_CONTACT_CATEGORIES_REJECTED =
  'GET_CONTACT_CATEGORIES_REJECTED';
export const CONTACT_CATEGORY_UNLOAD = 'CONTACT_CATEGORY_UNLOAD';
export const POST_CONTACT_CATEGORY = 'POST_CONTACT_CATEGORY';
export const POST_CONTACT_CATEGORY_FULFILLED =
  'POST_CONTACT_CATEGORY_FULFILLED';
export const POST_CONTACT_CATEGORY_REJECTED = 'POST_CONTACT_CATEGORY_REJECTED';
export const POST_CONTACT_CATEGORY_PENDING = 'POST_CONTACT_CATEGORY_PENDING';
export const UPDATE_CONTACT_CATEGORY = 'UPDATE_CONTACT_CATEGORY';
export const UPDATE_CONTACT_CATEGORY_FULFILLED =
  'UPDATE_CONTACT_CATEGORY_FULFILLED';
export const UPDATE_CONTACT_CATEGORY_REJECTED =
  'UPDATE_CONTACT_CATEGORY_REJECTED';
export const UPDATE_CONTACT_CATEGORY_PENDING =
  'UPDATE_CONTACT_CATEGORY_PENDING';
export const DETAIL_CONTACT_CATEGORY_FULFILLED =
  'DETAIL_CONTACT_CATEGORY_FULFILLED';
export const DETAIL_CONTACT_CATEGORY = 'DETAIL_CONTACT_CATEGORY';
export const DETAIL_CONTACT_CATEGORY_REJECTED =
  'DETAIL_CONTACT_CATEGORY_REJECTED';

/*
 *=================================================================================================
 *  User Report Constants
 *=================================================================================================
 */
export const GET_USER_REPORTS = 'GET_USER_REPORTS';
export const GET_USER_REPORTS_FULFILLED = 'GET_USER_REPORTS_FULFILLED';
export const GET_USER_REPORTS_REJECTED = 'GET_USER_REPORTS_REJECTED';
export const BLOCK_USER_REPORT = 'BLOCK_USER_REPORT';
export const BLOCK_USER_REPORT_FULFILLED = 'BLOCK_USER_REPORT_FULFILLED';
export const BLOCK_USER_REPORT_REJECTED = 'BLOCK_USER_REPORT_REJECTED';
export const USER_REPORT_UNLOAD = 'USER_REPORT_UNLOAD';

/*
 *=================================================================================================
 *  User Report Constants
 *=================================================================================================
 */
export const GET_USER_CHANCE_BUY = 'GET_USER_CHANCE_BUY';
export const GET_USER_CHANCE_BUY_FULFILLED = 'GET_USER_CHANCE_BUY_FULFILLED';
export const GET_USER_CHANCE_BUY_REJECTE = 'GET_USER_CHANCE_BUY_REJECTED';
export const GET_LOG_USER_CHANCE_BUY = 'GET_LOG_USER_CHANCE_BUY';
export const USER_CHANCE_BUY_UNLOAD = 'USER_CHANCE_BUY_UNLOAD';
export const GET_LOG_USER_CHANCE_BUY_FULFILLED =
  'GET_LOG_USER_CHANCE_BUY_FULFILLED';
export const GET_LOG_USER_CHANCE_BUY_REJECTE =
  'GET_LOG_USER_CHANCE_BUY_REJECTED';

/*
 *=================================================================================================
 *  Log User Coin Charge
 *=================================================================================================
 */
export const LOG_USER_COIN_CHARGE = 'LOG_USER_COIN_CHARGE';
export const LOG_USER_COIN_CHARGE_FULFILLED = 'LOG_USER_COIN_CHARGE_FULFILLED';
export const LOG_USER_COIN_CHARGE_REJECTED = 'LOG_USER_COIN_CHARGE_REJECTED';
export const LOG_USER_COIN_CHARGE_UNLOAD = 'LOG_USER_COIN_CHARGE_UNLOAD';

export const LOG_USER_POINT = 'LOG_USER_POINT';
export const LOG_USER_POINT_FULFILLED = 'LOG_USER_POINT_FULFILLED';
export const LOG_USER_POINT_REJECTED = 'LOG_USER_POINT_REJECTED';
export const LOG_USER_POINT_UNLOAD = 'LOG_USER_POINT_UNLOAD';
/*
 *=================================================================================================
 *  Log Discount ticket
 *=================================================================================================
 */
export const LOG_DISCOUNT_TICKET = 'LOG_DISCOUNT_TICKET';
export const LOG_DISCOUNT_TICKET_FULFILLED = 'LOG_DISCOUNT_TICKET_FULFILLED';
export const LOG_DISCOUNT_TICKET_REJECTED = 'LOG_DISCOUNT_TICKET_REJECTED';
export const LOG_DISCOUNT_TICKET_UNLOAD = 'LOG_DISCOUNT_TICKET_UNLOAD';

/*
 *=================================================================================================
 *  Log Product Favorite
 *=================================================================================================
 */
export const LOG_PRODUCT_FAVORITE = 'LOG_PRODUCT_FAVORITE';
export const LOG_PRODUCT_FAVORITE_FULFILLED = 'LOG_PRODUCT_FAVORITE_FULFILLED';
export const LOG_PRODUCT_FAVORITE_REJECTED = 'LOG_PRODUCT_FAVORITE_REJECTED';
export const LOG_PRODUCT_FAVORITE_UNLOAD = 'LOG_PRODUCT_FAVORITE_UNLOAD';

/*
 *=================================================================================================
 *  Log Friend
 *=================================================================================================
 */
export const LOG_FRIEND = 'LOG_FRIEND';
export const LOG_FRIEND_FULFILLED = 'LOG_FRIEND_FULFILLED';
export const LOG_FRIEND_REJECTED = 'LOG_FRIEND_REJECTED';
export const LOG_FRIEND_UNLOAD = 'LOG_FRIEND_UNLOAD';

export const LOG_AUCTION_WINNER_DEFAULT = 'LOG_AUCTION_WINNER_DEFAULT';
export const LOG_AUCTION_WINNER_DEFAULT_FULFILLED =
  'LOG_AUCTION_WINNER_DEFAULT_FULFILLED';
export const LOG_AUCTION_WINNER_DEFAULT_REJECTED =
  'LOG_AUCTION_WINNER_DEFAULT_REJECTED';

export const LOG_AUCTION_WINNER_SUCCESSFUL = 'LOG_AUCTION_WINNER_SUCCESSFUL';
export const LOG_AUCTION_WINNER_SUCCESSFUL_FULFILLED =
  'LOG_AUCTION_WINNER_SUCCESSFUL_FULFILLED';
export const LOG_AUCTION_WINNER_SUCCESSFUL_REJECTED =
  'LOG_AUCTION_WINNER_SUCCESSFUL_REJECTED';

export const LOG_AUCTION_WINNER_FAILS = 'LOG_AUCTION_WINNER_FAILS';
export const LOG_AUCTION_WINNER_FAILS_FULFILLED =
  'LOG_AUCTION_WINNER_FAILS_FULFILLED';
export const LOG_AUCTION_WINNER_FAILS_REJECTED =
  'LOG_AUCTION_WINNER_FAILS_REJECTED';

export const FILTER_LOG_AUCTION_WINNER = 'FILTER_LOG_AUCTION_WINNER';
export const FILTER_LOG_AUCTION_WINNER_FULFILLED =
  'FILTER_LOG_AUCTION_WINNER_FULFILLED';
export const FILTER_LOG_AUCTION_WINNER_REJECTED =
  'FILTER_LOG_AUCTION_WINNER_REJECTED';
